DELETE p1
FROM Person p1, Person p2
WHERE p1.Email = p2.Email 
AND p1.Id > p2.Id; 

OR

 with x AS (
SELECT  id
       ,ROW_NUMBER() OVER(PARTITION BY EMAIL ORDER BY ID ASC) AS RN
FROM PERSON) 

DELETE FROM Person WHERE id IN ( SELECT id FROM x WHERE RN >1) 